### ISSUE TITLE
Entire RadioGroup Item should be clickable and use pointer cursor

### ISSUE THREAD

**Issue by srindom** [medusajs/ui#89]
![CleanShot 2023-09-28 at 3 01 37](https://github.com/medusajs/ui/assets/7554214/7451c9a4-ef92-477e-a5ad-286f4928e43a)

**Comment by kasperkristensen** [comment]
The above is not a component from this library only the radios themselves. but since this will most likely be the most common way RadioGroups will be used I've added a new `RadioGroup.ChoiceBox` component, that has the above layout, and the correct behaviour with the entire component being clickable.
